 const quoteDisplayer = document.querySelector("#quoteDisplayer")
 const button = document.querySelector("#generateQuote")

let btn = document.getElementById('btn');
let output = document.getElementById('output');
let quotes = [
    '"Continuous improvement is better than delayed perfection." <br> - Mark Twain',
    '"When I let go of what I am, I become what I might be." <br> - Lao Tzu',
    '"Live your dream, and share your passion." <br> - Holstee Manifesto',
    '"Attitude is a little thing that makes a big difference." <br> - Winston Churchill',,
    '"Wherever you go, go with all your heart." <br> - Confucius',
    '"If people aren\'t laughing at your dreams, your dreams aren\'t big enough." <br> - Grayson Marshall',
    '"A person who never made a mistake never tried anything new." <br> - Albert Einstein',
    '"It\'s not what happens to you, but how you react to it that matters." <br> - Epictetus',
    '"Better to do something imperfectly than to do nothing flawlessly." <br> - Robert H. Schuller',
    '"The future depends on what we do in the present." <br> - Mahatma Gandhi',
    '"You can, you should, and if you\'re brave enough to start, you will." <br> - Stephen King',
    '"What do you do with a mistake: recognize it, admit it, learn from it, forget it." <br> - Dean Smith',
    '"Always remember that the future comes one day at a time." <br> - Dean Acheson',
    '"The smallest deed is better than the greatest intention." <br> - John Burroughs',
    '"Think lightly of yourself and deeply of the world." <br> - Miyamoto Musashi',
    '"Failure is success if you learn from it." <br> - Unknown',
    '"If you change nothing, nothing will change" <br> - Unknown',
    '"Don\'t let perfection become procrastination. Do it now." <br> - Danielle LaPorte',
    '"The wisest mind has something yet to learn." <br> - George Santayana',
    '"It takes as much energy to wish as it does to plan." <br> - Eleanor Roosevelt',
    '"Love the life you live. Live the life you love." <br> - Bob Marley',
    '"Kindness is as important as knowledge." <br> - Megan Smith',
    '"A smooth sea never made a skillful sailor." <br> - Proverb',
    '"Do something today that your future self will thank you for." <br> - Unknown',
    '"No matter what people tell you, words and ideas can change the world." <br> - Robin Williams',
    '"Great things are done by a series of small things brought together." <br> - Vincent Van Gogh',
    '"All things are difficult before they are easy." <br> - Thomas Fuller',
    '"Difficult roads often lead to beautiful destinations." <br> - Unknown',
    '"Inside of every problem lies an opportunity." <br> - Robert Kiyosaki',
    '"Always focus on how far you\'ve come, not how far you have to go." <br> - Anonymous',
    '"Nothing is particularly hard if you divide it into small jobs." <br> - Henry Ford',
    '"When you have a dream, you\'ve got to grab it and never let go." <br> - Carol Burnett',
    '"Nothing is impossible. The word itself says I\'m possible!" <br> - Audrey Hepburn',
    '"There is nothing impossible to they who will try." <br> - Alexander the Great',
    '"Keep your face always toward the sunshine, and shadows will fall behind you." <br> - Walt Whitman',
    '"You define your own life. Don\'t let other people write your script." <br> - Oprah Winfrey',
    '"You are never too old to set another goal or to dream a new dream." <br> - Malala Yousafzai',
    '"It is during our darkest moments that we must focus to see the light." <br> - Aristotle',
    '"Believe you can and you\'re halfway there." <br> - Theodore Roosevelt',
    '"Weaknesses are just strengths in the wrong environment." <br> - Marianne Cantwell',
    '"Try to be a rainbow in someone\'s cloud." <br> - Maya Angelou',
    '"Wake up determined, go to bed satisfied." <br> - Dwayne "The Rock" Johnson',
    '"Life is like riding a bicycle. To keep your balance, you must keep moving." <br> - Albert Einstein',
    '"Don\'t try to lessen yourself for the world; let the world catch up to you." <br> - Beyonce',
    '"If you don\'t like the road you\'re walking, start paving another one!" <br> - Dolly Parton',
    '"You are never too old to set another goal or to dream a new dream." <br> - C.S. Lewis',
    '"You have to be where you are to get where you need to go." <br> - Amy Poehler',
    '"The only limit to our realization of tomorrow will be our doubts today." <br> - Franklin Delano Roosevelt',
    '"You must find the place inside yourself where nothing is impossible." <br> - Deepak Chopra',
    '"Perfection is not attainable, but if we chase perfection we can catch excellence." <br> - Vince Lombardi',
    '"In order for the light to shine so brightly, the darkness must be present." <br> - Sir Francis Bacon',
    '"Never bend your head. Always hold it high. Look the world straight in the eye." <br> - Helen Keller',
    '"The only journey is the one within." <br> - Rainer Maria Rilke',
    '"All our dreams can come true, if we have the courage to pursue them." <br> - Walt Disney',
    '"The secret of getting ahead is getting started." <br> - Mark Twain',
    '"If people are doubting how far you can go, go so far that you can\'t hear them anymore." <br> - Michele Ruiz',
    '"Do one thing every day that scares you." <br> - Eleanor Roosevelt',
    '"Impossible is just an opinion." <br> - Paulo Coelho',
    '"Your passion is waiting for your courage to catch up." <br> - Isabelle Lafleche',
    '"If something is important enough, even if the odds are stacked against you, you should still do it." <br> - Elon Musk',
    '"Hold the vision, trust the process." <br> - Unknown',
    '"Don\'t be afraid to give up the good to go for the great." <br> - John D. Rockefeller',
    '"People who wonder if the glass is half empty or full miss the point. The glass is refillable." <br> - Unknown',
    '"One day or day one. You decide." <br> - Unknown',
    '"The hard days are what make you stronger." <br> - Aly Raisman',
    '"Keep your eyes on the stars, and your feet on the ground." <br> - Theodore Roosevelt',
    '"You can waste your lives drawing lines. Or you can live your life crossing them." <br> - Shonda Rhimes',
    '"If opportunity doesn\'t knock, build a door." <br> - Kurt Cobain',
    '"Work hard in silence, let your success be the noise." <br> - Frank Ocean',
    '"If everything seems to be under control, you\'re not going fast enough." <br> - Mario Andretti',
    '"The only difference between ordinary and extraordinary is that little extra." <br> - Jimmy Johnson',
    '"Never stop doing your best just because someone doesn\'t give you credit." <br> - Kamari',
    '"Start where you are. Use what you have. Do what you can." <br> - Arthur Ashe',
    '"Go the extra mile. It\'s never crowded there." <br> - Dr. Wayne D. Dyer',
    '"Make each day your masterpiece." <br> - John Wooden',
    '"Every champion was once a contender that didn\'t give up." <br> - Gabby Douglas',
    '"Don\'t dream about success. Get out there and work for it." <br> - Unknown',
    '"If you want to fly, give up everything that weighs you down." <br> - Buddha',
    '"Doubt kills more dreams than failure ever will." <br> - Suzy Kassem',
    '"I never lose. Either I win or learn." <br> - Nelson Mandela',
    '"Today is your opportunity to build the tomorrow you want." <br> - Ken Poirot',
    '"You\'re so much stronger than your excuses." <br> - Unknown',
    '"Don\'t tell everyone your plans, instead show them your results." <br> - Unknown',
    '"Nothing can dim the light that shines from within." <br> - Maya Angelou',
    '"Be so good they can\'t ignore you." <br> - Steve Martin',
    '"Do what you can, with what you have, where you are." <br> - Theodore Roosevelt',
    '"It\'s never too late to be what you might\'ve been." <br> - George Eliot',
    '"You can do anything you set your mind to." <br> - Benjamin Franklin',
    '"You never know what you can do until you try." <br> - William Cobbett',
    '"The world is full of nice people. If you can\'t find one, be one." <br> - Nishan Panwar',
    '"I can and I will. Watch me." <br> - Carrie Green',
    '"A winner is a dreamer who never gives up." <br> - Nelson Mandela',
    '"What is life without a little risk?" <br> - J.K. Rowling',
    '"There is some good in this world, and it\'s worth fighting for."<br> - J.R.R. Tolkien',
    '"Remember you\'re the one who can fill the world with sunshine." <br> - Snow White and the Seven Dwarfs',
    '"The world is changed by your example, not by your opinion." <br> - Paulo Coelho',
    '"Be the change you want to see in the world." <br> - Mahatma Gandhi',
    '"Believe you can and you will." <br> - Unknown',
    '"Do the right thing even when no one is looking." <br> - Unknown',
    '"Make today the day you learn something new." <br> - Unknown',
    '"It\'s not what happens to you but how you react to it that matters." <br> - Epictetus',
    '"You don\'t have to be perfect to be amazing." <br> - Unknown',
    '"The best way to predict your future is to create it." <br> - Abraham Lincoln',
    '"You must do the kind of things you think you cannot do." <br> - Eleanor Roosevelt',
    '"Practice makes progress, not perfect." <br> - Unknown',
    '"You may be disappointed if you fail, but you\'ll be doomed if you don\'t try." <br> - Beverly Sills',
    '"If you want to achieve greatness stop asking for permission." <br> - "Anonymous',
    '"All our dreams can come true if we have the courage to pursue them." <br> - Walt Disney',
    '"Opportunities don\'t happen, you create them." <br> - Chris Grosser',
    '"One small positive thought can change your whole day." <br> - Zig Ziglar',
    '"Be positive. Be true. Be kind." <br> - Roy T. Bennett',
    '"If you are positive, you\'ll see opportunities instead of obstacles." <br> - Widad Akrawi',
    '"Accentuate the positive, eliminate the Negative, latch onto the affirmative." <br> - Bing Crosby',
    '"Keep a smile on your face. Keep a spring in your step." <br> - Joel Osteen',
    '"Turn every life situation into a positive one." <br> - Rhonda Byrne',
    '"Don\'t focus on negative things; focus on the positive, and you will flourish." <br> - Alek Wek',
    '"Surround yourself with positive people and you\'ll be a positive person." <br> - Kellie Pickler',
    '"It\'s almost always possible to be honest and positive." <br> - Naval Ravikant',
    '"The less you respond to negative people, the more positive your life will become." <br> - Paolo Coelho',
    '"Change your thoughts and you can change your world." <br> - Norman Vincent Peale',
    '"Shoot for the moon. Even if you miss, you\'ll land among the stars." <br> - Norman Vincent Peale',
    '"Believing in negative thoughts is the single greatest obstruction to success." <br> - Charles F. Glassman',
    '"Every day may not be good… but there\'s something good in every day." <br> - Alice Morse Earle',
    '"A problem is a chance for you to do your best." <br> - Duke Ellington',
    '"I think positive emotion trumps negative emotion every time." <br> - Leonardo DiCaprio',
    '"When it rains, look for rainbows; when it\'s dark, look for stars." <br> - Unknown',
    '"The best thing to hold onto in life is each other." <br> - Audrey Hepburn',
    '"The only impossible journey is the one you never begin." <br> - Tony Robbins',
    '"When you know what you want, and want it bad enough, you\'ll find a way to get it." <br> - Jim Rohn',
    '"Go confidently in the direction of your dreams. Live the life you have imagined." <br> - Henry David Thoreau',
    '"Take action. An inch of movement will bring you closer to your goals than a mile of intention." <br> - Steve Maraboli',
    '"You miss 100% of the shots you don\'t take." <br> - Wayne Gretzkyv',
    '"Everything you\'ve ever wanted is on the other side of fear." <br> - George Addair',
    '"It\'s during our darkest moments that we must focus to see the light." <br> - Aristotle',
    '"It is never too late to be what you might have been." <br> - George Eliot',
    '"Live as if you were to die tomorrow. Learn as if you were to live forever." <br> - Mahatma Gandhi',
    '"That which does not kill us makes us stronger." <br> - Friedrich Nietzsche',
    '"We must not allow other people\'s limited perceptions to define us." <br> - Virginia Satir',
    '"Do what you can, with what you have, where you are." <br> - Theodore Roosevelt',
    '"Be yourself; everyone else is already taken." <br> - Oscar Wilde',
    '"If you cannot do great things, do small things in a great way." <br> - Napoleon Hill',
    '"Do not let what you cannot do interfere with what you can do." <br> - John Wooden',
    '"Whenever you find yourself on the side of the majority, it is time to pause and reflect." <br> - Mark Twain',
    '"Either you run the day, or the day runs you." <br> - Jim Rohn',
    '"Believe and act as if it were impossible to fail." <br> - Charles Kettering',
    '"The best way to predict the future is to invent it." <br> - Alan Kay',
    '"Everything has beauty, but not everyone can see." <br> - Confucius',
    '"Believe you can and you\'re halfway there." <br> - Theodore Roosevelt',
    '"How wonderful it is that nobody need wait a single moment before starting to improve the world." <br> - Anne Frank',
    '"Happiness is not something ready made. It comes from your own actions." <br> - Dalai Lama',
    '"Remember that happiness is a way of travel, not a destination." <br> - Roy M. Goodman',
    '"Too many of us are not living our dreams because we are living our fears." <br> - Les Brown',
    '"If you want to lift yourself up, lift up someone else." <br> - Booker T. Washington',
    '"To live is the rarest thing in the world. Most people exist, that is all." <br> - Oscar Wilde',
    '"There are two ways of spreading light: to be the candle or the mirror that reflects it." <br> - Edith Wharton',
    '"Walking with a friend in the dark is better than walking alone in the light." <br> - Helen Keller',
    '"Happiness is not a goal; it is a by-product." <br> - Eleanor Roosevelt',
    '"Life has no limitations, except the ones you make." <br> - Les Brown',
    '"The greatest glory in living lies not in never falling, but in rising every time we fall." <br> - Nelson Mandela',
    '"Spread love everywhere you go. Let no one ever come to you without leaving happier" <br> - "Mother Teresa',
    '"It\'s not the years in your life that count. It\'s the life in your years." <br> - Edward J. Stieglitz',
    '"Balance achievement with appreciation." <br> - Tim Ferriss',
    '"Failure is just practice for success." <br> - Unknown',
    '"Rise above the storm and you will find the sunshine." <br> - Mario Fernandez',
    '"A stumble may prevent a fall." <br> - Gretchen Rubin',
    '"Dreams are made possible if you try." <br> - Terry Fox',
    '"Daily ripples of excellence over time become a tsunami of success." <br> - Robin S. Sharma',
    '"Today I will do what others won\'t, so tomorrow I can do what others can\'t." <br> - Jerry Rice',
    '"Give thanks for a little and you will find a lot." <br> - Hansa Proverb',
    '"Do more of what makes you happy." <br> - Unknown',
    '"The past is done. The future has plenty of room for change." <br> - Unknown',
    '"If you get tired, learn to rest, not to quit." <br> - Banksy',
    '"It always seems impossible until it\'s done." <br> - Nelson Mandela',
    '"You don\'t have to see the whole staircase. Just take the first step." <br> - Martin Luther King',
    '"The penalty for procrastination is the loss of hopes and dreams." <br> - Tai Lopez',
    '"Be focused. Be determined. Be hopeful. Be empowered." <br> - Michelle Obama',   /* XXXXX */
    '"Your big opportunity may be right where you are now." <br> - Napoleon Hill',
    '"Attitude is a little thing that makes a big difference." <br> - Winston Churchill',
    '"The mind is everything. What you think you become." <br> - Buddha',
    '"The only real mistake is the one from which we learn nothing." <br> - Henry Ford',
    '"A year from now you will wish you had started today." <br> - Karen Lamb',
    '"Try and fail, but don\'t fail to try." <br> - Stephen Kaggwa',
    '"Experience is simply the name we give our mistakes." <br> - Oscar Wilde',
    '"The future depends on what we do in the present." <br> - Mahatma Gandhi',
    '"If you can imagine it, you can achieve it. If you can dream it, you can become it." <br> - William Arthur Ward',
    '"Attitude is a choice. Think positive thoughts daily. Believe in yourself." <br> - Pat Summitt',
    '"You got this. Make it happen." <br> - Danielle LaPorte',
    '"An investment in knowledge pays the best interest." <br> - Benjamin Franklin',
    '"The best way to not feel hopeless is to get up and do something." <br> - Barack Obama',
    '"Victory is sweetest when you\'ve known defeat." <br> - Malcolm Forbes',
    '"Talent is a pursued interest. Anything that you\'re willing to practice, you can do." <br> - Bob Ross',
    '"“Don\'t think about what might go wrong, think about what could be right." <br> - Unknown'
];

var randomQuote = quotes[Math.floor(Math.random() * quotes.length)]
quoteDisplayer.innerHTML = randomQuote;

btn.addEventListener('click', function(){
    var randomQuote = quotes[Math.floor(Math.random() * quotes.length)]
    quoteDisplayer.innerHTML = randomQuote;
})
